name: codecov-go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: codecov
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.4

    - name: Install dependencies
      run: go get -u ./...

    - name: Build Monitor
      run: go build -o ./cmd/monitor/monitor ./cmd/monitor/*.go

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./... -coverpkg=./...
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
