name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.55.2
          #version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0
          # -E musttag returns "[runner] Can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1"
          #args: -v -E goerr113 -E asasalint -E asciicheck -E bidichk -E bodyclose -E containedctx -E contextcheck -E cyclop -E deadcode -E decorder -E dogsled -E dupl -E dupword -E durationcheck -E errchkjson -E errname -E errorlint -E execinquery -E exhaustive -E exhaustruct -E exportloopref -E forbidigo -E forcetypeassert -E funlen -E gci -E ginkgolinter -E gocheckcompilerdirectives -E gochecknoinits -E gocognit -E goconst -E gocritic -E gocyclo -E godot -E godox -E gofmt -E gofumpt -E goheader -E goimports -E golint -E gomnd -E gomoddirectives -E gomodguard -E goprintffuncname -E gosec -E gosmopolitan -E grouper -E importas -E interfacebloat -E interfacer -E ireturn -E lll -E loggercheck -E maintidx -E makezero -E maligned -E mirror -E misspell -E nakedret -E nestif -E nilerr -E nilnil -E nlreturn -E noctx -E nolintlint -E nonamedreturns -E nosnakecase -E nosprintfhostport -E prealloc -E predeclared -E promlinter -E reassign -E revive -E rowserrcheck -E scopelint -E sqlclosecheck -E structcheck -E stylecheck -E tagalign -E tagliatelle -E tenv -E testableexamples -E testpackage -E thelper -E tparallel -E unconvert -E unparam -E usestdlibvars -E varcheck -E varnamelen -E wastedassign -E whitespace -E wrapcheck -E zerologlint -E ifshort
          #args: --enable-all --disable gochecknoglobals --disable paralleltest --disable exhaustivestruct --disable depguard --disable wsl --disable ifshort
          args: -v

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: false

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
